# Generated by Django 4.1.1 on 2022-10-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatenfood',
            old_name='name',
            new_name='food',
        ),
    ]
