# Generated by Django 4.1.1 on 2022-10-10 14:26

from django.db import migrations

def create_bars(apps, schema_editor):
    Food = apps.get_model('calories', 'Food')
    FoodCategory = apps.get_model('calories', 'FoodCategory')
    default_category, _ = FoodCategory.objects.get_or_create(name='x3')
    for food in Food.objects.all():
        food.category = default_category
        food.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_foodcategory_food_category'),
    ]

    operations = [
        migrations.RunPython(create_bars)
    ]
