# Generated by Django 4.1.1 on 2022-11-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_alter_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatenfood',
            old_name='user_eaten',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='user_added',
            new_name='user',
        ),
    ]
